# Generated by Django 4.0.3 on 2023-04-16 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edusol_app', '0002_courseandcodes_finalallotments1922_maxmincutoff1922_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('name', models.TimeField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, primary_key=True, serialize=False)),
                ('maths', models.IntegerField(blank=True)),
                ('physics', models.IntegerField(blank=True)),
                ('chemistry', models.IntegerField(blank=True)),
            ],
            options={
                'db_table': 'user',
                'managed': False,
            },
        ),
    ]
