# Generated by Django 4.0.3 on 2023-04-22 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edusol_app', '0003_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('name', models.TextField(blank=True, null=True)),
                ('email', models.TextField(primary_key=True, serialize=False)),
                ('maths', models.TextField()),
                ('physics', models.TextField()),
                ('chemistry', models.TextField()),
            ],
            options={
                'db_table': 'users',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
