# Generated by Django 4.0.3 on 2023-04-27 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edusol_app', '0004_users_delete_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collegenameoption',
            fields=[
                ('collegename', models.TextField(blank=True, db_column='CollegeName', null=True)),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'collegenameoption',
                'managed': False,
            },
        ),
    ]
